"""manufacturing_abdelhafidh.py - Phase 5 custom project.

Applies the same OLAP reporting techniques used in olap_case.py
(slice, dice, roll-up, drill-down, and a top-N ranking) to a
DIFFERENT business problem: manufacturing process engineering.

Instead of retail sales, this script analyzes daily production
records across multiple production lines, shifts, and machines,
answering questions a plant manager or process engineer would
actually ask:

- Which shift produces the most defects on our worst-performing
  production line? (slice)
- How do downtime and output compare across selected lines and
  shifts? (dice)
- How does total downtime trend from month to quarter to year? (roll-up)
- Which months in the most recent year had the worst downtime? (drill-down)
- Which individual machines cause the most downtime overall? (top-N)

Author: Abdelhafidh Mahouel
Date: 2026-08

Data Source:
- data/manufacturing/manufacturing_process_abdelhafidh.csv
  (synthetic data, generated by generate_manufacturing_data.py)

Output:
- data/reporting/manufacturing_reporting_abdelhafidh.csv

Terminal command to run this file from the root project folder:

uv run python -m bizintel.manufacturing_abdelhafidh
"""

# === IMPORTS ===

from pathlib import Path
from typing import Final

import duckdb
import matplotlib.pyplot as plt
import pandas as pd

from bizintel.utils_logger import LOG, log_header
from bizintel.utils_viz import plot_bar, plot_line

# === CONSTANTS ===

# Raw manufacturing data (generated separately, see
# generate_manufacturing_data.py).
RAW_FILE: Final[Path] = Path("data/manufacturing/manufacturing_process_abdelhafidh.csv")

DATA_REPORTING: Final[Path] = Path("data/reporting")
REPORTING_FILE: Final[Path] = DATA_REPORTING / "manufacturing_reporting_abdelhafidh.csv"

# Slice: focus on one production line (the one with the most
# known issues) and compare shifts within it.
SLICE_LINE: Final[str] = "Line-C"

# Dice: compare a targeted subset of lines and shifts.
DICE_LINES: Final[tuple[str, ...]] = ("Line-C", "Line-B")
DICE_SHIFTS: Final[tuple[str, ...]] = ("Morning", "Night")

# Top-N: how many worst-performing machines to rank by downtime.
TOP_N_MACHINES: Final[int] = 5


# === SECTION 1: LOAD DATA AND CREATE A REPORTING VIEW ===


def create_reporting_view(conn: duckdb.DuckDBPyConnection) -> None:
    """Load the raw CSV and create a reporting view with time fields.

    WHY: Manufacturing data is time-stamped at the day level.
    Adding Year, Quarter, and YearMonth columns up front lets every
    downstream OLAP query (roll-up, drill-down) reuse the same
    time hierarchy instead of recomputing it in each query.

    Args:
        conn: Open in-memory DuckDB connection.

    Returns:
        None
    """
    LOG.info("Creating the manufacturing_reporting view")

    sql = f"""
        CREATE OR REPLACE VIEW manufacturing_reporting AS
        SELECT
            RecordID,
            CAST(ProductionDate AS DATE) AS ProductionDate,
            CAST(EXTRACT(YEAR FROM CAST(ProductionDate AS DATE)) AS INTEGER)
                AS ProdYear,
            CAST(EXTRACT(QUARTER FROM CAST(ProductionDate AS DATE)) AS INTEGER)
                AS ProdQuarter,
            STRFTIME(CAST(ProductionDate AS DATE), '%Y-%m') AS YearMonth,
            ProductionLine,
            Shift,
            MachineID,
            OperatorID,
            UnitsProduced,
            DefectiveUnits,
            DowntimeMinutes,
            CycleTimeSeconds,
            ProcessTempC
        FROM read_csv_auto('{RAW_FILE.as_posix()}')
    """

    conn.execute(sql)
    LOG.info("  manufacturing_reporting view created")


def export_reporting_dataset(
    conn: duckdb.DuckDBPyConnection,
) -> pd.DataFrame:
    """Export the reporting view to a CSV file.

    Args:
        conn: Open DuckDB connection.

    Returns:
        Reporting-ready pandas DataFrame.
    """
    LOG.info("Exporting the reporting-ready dataset")
    DATA_REPORTING.mkdir(parents=True, exist_ok=True)

    sql = """
        SELECT *
        FROM manufacturing_reporting
        ORDER BY ProductionDate, RecordID
    """
    df_reporting: pd.DataFrame = conn.execute(sql).df()
    df_reporting.to_csv(REPORTING_FILE, index=False)

    LOG.info(f"  Exported {df_reporting.shape[0]} reporting rows")
    return df_reporting


# === SECTION 2: SLICE - one production line, compare shifts ===


def slice_defects_by_shift(
    conn: duckdb.DuckDBPyConnection,
    selected_line: str,
) -> pd.DataFrame:
    """Slice: fix one production line, compare defect rate by shift.

    Args:
        conn: Open DuckDB connection.
        selected_line: Production line to include in the slice.

    Returns:
        DataFrame with Shift, TotalUnits, TotalDefective, and
        DefectRatePct columns.
    """
    LOG.info(f"OLAP slice: defect rate by Shift for {selected_line!r}")

    sql = """
        SELECT
            Shift,
            SUM(UnitsProduced) AS TotalUnits,
            SUM(DefectiveUnits) AS TotalDefective,
            ROUND(
                100.0 * SUM(DefectiveUnits) / NULLIF(SUM(UnitsProduced), 0),
                2
            ) AS DefectRatePct
        FROM manufacturing_reporting
        WHERE ProductionLine = ?
        GROUP BY Shift
        ORDER BY DefectRatePct DESC
    """
    df_slice: pd.DataFrame = conn.execute(sql, [selected_line]).df()

    if df_slice.empty:
        raise ValueError(f"No records found for line {selected_line!r}.")

    LOG.info(f"  Shifts in the slice: {df_slice.shape[0]}")
    return df_slice


# === SECTION 3: DICE - selected lines and shifts ===


def dice_downtime_by_line_shift(
    conn: duckdb.DuckDBPyConnection,
    selected_lines: tuple[str, ...],
    selected_shifts: tuple[str, ...],
) -> pd.DataFrame:
    """Dice: compare total downtime across selected lines and shifts.

    Args:
        conn: Open DuckDB connection.
        selected_lines: Production lines to include.
        selected_shifts: Shifts to include.

    Returns:
        DataFrame with ProductionLine, Shift, and TotalDowntimeMinutes.
    """
    LOG.info(f"OLAP dice: Lines = {selected_lines}; Shifts = {selected_shifts}")

    sql = """
        SELECT
            ProductionLine,
            Shift,
            SUM(DowntimeMinutes) AS TotalDowntimeMinutes
        FROM manufacturing_reporting
        WHERE ProductionLine IN (?, ?)
          AND Shift IN (?, ?)
        GROUP BY ProductionLine, Shift
        ORDER BY TotalDowntimeMinutes DESC
    """
    parameters = [*selected_lines, *selected_shifts]
    df_dice: pd.DataFrame = conn.execute(sql, parameters).df()

    if df_dice.empty:
        raise ValueError("The selected dice returned no rows.")

    LOG.info(f"  Line-shift combinations: {df_dice.shape[0]}")
    return df_dice


# === SECTION 4: ROLL-UP - downtime through the time hierarchy ===


def rollup_downtime_by_time(conn: duckdb.DuckDBPyConnection) -> pd.DataFrame:
    """Roll up total downtime minutes through Month -> Quarter -> Year -> All.

    Args:
        conn: Open DuckDB connection.

    Returns:
        DataFrame with downtime totals at each summary level.
    """
    LOG.info("OLAP roll-up: Month -> Quarter -> Year -> All")

    sql = """
        SELECT
            CASE
                WHEN ProdYear IS NULL THEN 'All Time'
                WHEN ProdQuarter IS NULL THEN 'Year'
                WHEN YearMonth IS NULL THEN 'Quarter'
                ELSE 'Month'
            END AS SummaryLevel,
            ProdYear,
            ProdQuarter,
            YearMonth,
            ROUND(SUM(DowntimeMinutes), 2) AS TotalDowntimeMinutes
        FROM manufacturing_reporting
        GROUP BY ROLLUP (ProdYear, ProdQuarter, YearMonth)
        ORDER BY
            ProdYear NULLS LAST,
            ProdQuarter NULLS LAST,
            YearMonth NULLS LAST
    """
    df_rollup: pd.DataFrame = conn.execute(sql).df()

    LOG.info(f"  Roll-up rows returned: {df_rollup.shape[0]}")
    return df_rollup


# === SECTION 5: DRILL-DOWN - detail behind the most recent year ===


def get_latest_year(conn: duckdb.DuckDBPyConnection) -> int:
    """Find the most recent production year for drill-down."""
    sql = "SELECT MAX(ProdYear) FROM manufacturing_reporting"
    return int(conn.execute(sql).fetchone()[0])


def drilldown_downtime_by_time(
    conn: duckdb.DuckDBPyConnection,
    selected_year: int,
) -> pd.DataFrame:
    """Drill down from one year into quarterly and monthly downtime detail.

    Args:
        conn: Open DuckDB connection.
        selected_year: Year to drill into.

    Returns:
        DataFrame with quarterly and monthly downtime totals.
    """
    LOG.info(f"OLAP drill-down: Year {selected_year} -> Quarter -> Month")

    sql = """
        WITH selected AS (
            SELECT *
            FROM manufacturing_reporting
            WHERE ProdYear = ?
        )
        SELECT
            'Month' AS DetailLevel,
            YearMonth AS PeriodLabel,
            ProdQuarter,
            ROUND(SUM(DowntimeMinutes), 2) AS TotalDowntimeMinutes
        FROM selected
        GROUP BY YearMonth, ProdQuarter
        ORDER BY YearMonth
    """
    df_drilldown: pd.DataFrame = conn.execute(sql, [selected_year]).df()

    if df_drilldown.empty:
        raise ValueError(f"No records found for year {selected_year}.")

    LOG.info(f"  Drill-down rows returned: {df_drilldown.shape[0]}")
    return df_drilldown


# === SECTION 6: TOP-N - worst machines by total downtime ===


def top_machines_by_downtime(
    conn: duckdb.DuckDBPyConnection,
    top_n: int,
) -> pd.DataFrame:
    """Rank individual machines by total downtime and return the top N.

    WHY: This is the same "leaderboard" OLAP pattern used for
    top_products_by_sales() in olap_abdelhafidh.py, applied here to
    identify which machines a maintenance team should prioritize.

    Args:
        conn: Open DuckDB connection.
        top_n: Number of worst-performing machines to return.

    Returns:
        DataFrame with MachineID, ProductionLine, and
        TotalDowntimeMinutes, sorted descending, limited to top_n.
    """
    LOG.info(f"OLAP top-N: ranking machines by downtime (top {top_n})")

    sql = """
        SELECT
            MachineID,
            ProductionLine,
            ROUND(SUM(DowntimeMinutes), 2) AS TotalDowntimeMinutes
        FROM manufacturing_reporting
        GROUP BY MachineID, ProductionLine
        ORDER BY TotalDowntimeMinutes DESC
        LIMIT ?
    """
    df_top: pd.DataFrame = conn.execute(sql, [top_n]).df()

    if df_top.empty:
        raise ValueError("No machine downtime records were found.")

    LOG.info(f"  Top machines returned: {df_top.shape[0]}")
    return df_top


# === SECTION 7: SUMMARIZE ===


def summarize(
    df_slice: pd.DataFrame,
    df_dice: pd.DataFrame,
    df_rollup: pd.DataFrame,
    df_drilldown: pd.DataFrame,
    df_top_machines: pd.DataFrame,
    selected_line: str,
    selected_year: int,
) -> None:
    """Log a brief summary of the manufacturing OLAP findings."""
    LOG.info("========================")
    LOG.info("SUMMARY")
    LOG.info("========================")

    worst_shift = str(df_slice.iloc[0]["Shift"])
    worst_shift_rate = float(df_slice.iloc[0]["DefectRatePct"])
    LOG.info(
        f"Slice: On {selected_line}, the {worst_shift} shift has the "
        f"highest defect rate ({worst_shift_rate}%)"
    )

    top_dice_line = str(df_dice.iloc[0]["ProductionLine"])
    top_dice_shift = str(df_dice.iloc[0]["Shift"])
    top_dice_minutes = float(df_dice.iloc[0]["TotalDowntimeMinutes"])
    LOG.info(
        "Dice: The most downtime among selected combinations is "
        f"{top_dice_line} / {top_dice_shift} "
        f"({top_dice_minutes:,.0f} minutes)"
    )

    df_all_time = df_rollup.loc[df_rollup["SummaryLevel"] == "All Time"]
    all_time_minutes = float(df_all_time.iloc[0]["TotalDowntimeMinutes"])
    LOG.info(
        f"Roll-up: Total downtime across all time is {all_time_minutes:,.0f} minutes"
    )

    worst_month_index = df_drilldown["TotalDowntimeMinutes"].idxmax()
    worst_month = str(df_drilldown.loc[worst_month_index, "PeriodLabel"])
    worst_month_minutes = float(
        df_drilldown.loc[worst_month_index, "TotalDowntimeMinutes"]
    )
    LOG.info(
        f"Drill-down: The worst month for downtime in {selected_year} is "
        f"{worst_month} ({worst_month_minutes:,.0f} minutes)"
    )

    worst_machine = str(df_top_machines.iloc[0]["MachineID"])
    worst_machine_line = str(df_top_machines.iloc[0]["ProductionLine"])
    worst_machine_minutes = float(df_top_machines.iloc[0]["TotalDowntimeMinutes"])
    LOG.info(
        "Top Machine: The machine causing the most downtime overall is "
        f"{worst_machine} on {worst_machine_line} "
        f"({worst_machine_minutes:,.0f} minutes)"
    )

    LOG.info("========================")
    LOG.info("ENGINEER NOTES:")
    LOG.info("Use slice to focus on one production line.")
    LOG.info("Use dice to compare a targeted subset of lines and shifts.")
    LOG.info("Use roll-up to move from daily detail to broader summaries.")
    LOG.info("Use drill-down to investigate the detail behind a summary.")
    LOG.info("Use a top-N ranking to prioritize maintenance attention.")
    LOG.info("========================")


# === MAIN FUNCTION ===


def main() -> None:
    """Main function to run the manufacturing OLAP analysis."""
    log_header(LOG, "MFG")

    LOG.info("========================")
    LOG.info("START main()")
    LOG.info("========================")

    if not RAW_FILE.exists():
        raise FileNotFoundError(
            f"Manufacturing data not found: {RAW_FILE}. "
            "Run generate_manufacturing_data.py first."
        )

    LOG.info("Connecting to in-memory DuckDB........")
    conn: duckdb.DuckDBPyConnection = duckdb.connect()

    try:
        LOG.info("CALL a function to create the reporting view........")
        create_reporting_view(conn)

        LOG.info("CALL a function to export reporting data........")
        export_reporting_dataset(conn)

        LOG.info("CALL a function to slice defects by shift........")
        df_slice = slice_defects_by_shift(conn, SLICE_LINE)

        LOG.info("CALL a function to plot the slice result........")
        plot_bar(
            df=df_slice,
            x="Shift",
            y="DefectRatePct",
            title=f"Defect Rate by Shift on {SLICE_LINE}",
            xlabel="Shift",
            ylabel="Defect Rate (%)",
            palette="Reds_d",
        )

        LOG.info("CALL a function to dice downtime by line and shift........")
        df_dice = dice_downtime_by_line_shift(conn, DICE_LINES, DICE_SHIFTS)

        df_dice_chart = df_dice.copy()
        df_dice_chart["LineShift"] = (
            df_dice_chart["ProductionLine"] + " / " + df_dice_chart["Shift"]
        )

        LOG.info("CALL a function to plot the dice result........")
        plot_bar(
            df=df_dice_chart,
            x="LineShift",
            y="TotalDowntimeMinutes",
            title="Downtime for Selected Lines and Shifts",
            xlabel="Line / Shift",
            ylabel="Total Downtime (minutes)",
            palette="Oranges_d",
        )

        LOG.info("CALL a function to rank worst machines by downtime........")
        df_top_machines = top_machines_by_downtime(conn, TOP_N_MACHINES)

        LOG.info("CALL a function to plot the top-machines result........")
        plot_bar(
            df=df_top_machines,
            x="MachineID",
            y="TotalDowntimeMinutes",
            title=f"Top {TOP_N_MACHINES} Machines by Total Downtime",
            xlabel="Machine",
            ylabel="Total Downtime (minutes)",
            palette="Purples_d",
        )

        LOG.info("CALL a function to roll up downtime by time........")
        df_rollup = rollup_downtime_by_time(conn)

        df_quarterly = df_rollup.loc[df_rollup["SummaryLevel"] == "Quarter"].copy()
        df_quarterly["YearQuarter"] = (
            df_quarterly["ProdYear"].astype(int).astype(str)
            + "-Q"
            + df_quarterly["ProdQuarter"].astype(int).astype(str)
        )

        LOG.info("CALL a function to plot quarterly roll-up results........")
        plot_line(
            df=df_quarterly,
            x="YearQuarter",
            y="TotalDowntimeMinutes",
            title="Quarterly Downtime Roll-Up",
            xlabel="Quarter",
            ylabel="Total Downtime (minutes)",
        )

        LOG.info("CALL a function to select a drill-down year........")
        selected_year = get_latest_year(conn)

        LOG.info("CALL a function to drill down by time........")
        df_drilldown = drilldown_downtime_by_time(conn, selected_year)

        LOG.info("CALL a function to plot monthly drill-down results........")
        plot_line(
            df=df_drilldown,
            x="PeriodLabel",
            y="TotalDowntimeMinutes",
            title=f"Monthly Downtime Drill-Down for {selected_year}",
            xlabel="Month",
            ylabel="Total Downtime (minutes)",
        )

        LOG.info("CALL a function to summarize findings........")
        summarize(
            df_slice,
            df_dice,
            df_rollup,
            df_drilldown,
            df_top_machines,
            SLICE_LINE,
            selected_year,
        )

        LOG.info("CALL a function to show charts........")
        plt.show()

    finally:
        conn.close()
        LOG.info("Closed DuckDB connection")

    LOG.info("Workflow complete")
    LOG.info("CLOSE chart windows to continue.")
    LOG.info("========================")
    LOG.info("Executed successfully!")
    LOG.info("========================")


if __name__ == "__main__":
    main()
